---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    # - name: Update and upgrade
    #   apt:
    #     update_cache: yes
    #     upgrade: yes
    #     force_apt_get: yes
    - name: Install python3-tk
      apt:
        name: 
          - python3-tk
        state: latest
        update_cache: yes
        force_apt_get: yes
