# Make nodes satisfy roles
- name: Apply Common Configuration To All Nodes
  hosts: all
  roles:
    # Configure all the disks first, because filesystem permissions and whatnot
    # one those mount points get configured after in the common role
    - role: data-disks
      tags: ['disk']
    - role: common
      tags: ['common']

- name: Setup login node
  hosts: login
  roles:
    - role: login
      tags: ['login']

- name: Setup compute nodes
  hosts: compute
  vars:
    dask_scheduler_ip_address: "{{ hostvars['headnode']['ansible_facts']['default_ipv4']['address'] }}"
  roles:
    - role: compute
      tags: ['compute']
