#####################################################################################################
# Script: cluster.yaml
# Author: Kyle Robertson
# Date: September 18, 2015
# Company: Worlcom Exchange Inc.
# Description: A HEAT template that deploys the networking resources for the autoscale_cluster_yaml
# stack
#####################################################################################################

heat_template_version: 2014-10-16
description: Homogenous compute cluster

parameters:
    # Networking parameters
    external_network:
      type: string
      label: External Network UUID
      description: UUID of the external network where floating IP's for environment exist
    internal_network:
      type: string
      label: Interal Network UUID
      description: UUID of the internal network for the cluster
      default: igk-402_network
    security_group:
      type: string
      label: Instance Security Group
      description: Name of security group to place all instances in
      default: default
    # Computing parameters
    cluster_size:
      type: number
      description: Minimum number of servers in the compute node cluster
      constraints:
        - range: {min: 2, max: 20}
      default: 2
    image:
      type: string
      label: Image name or ID
      description: Bootable image used to boot all instances
      default: CentOS 7
    compute_flavor:
      type: string
      label: Instance flavor
      description: Type of flavor that defines virtual resources for compute nodes
      constraints:
        - allowed_values: 
          - p4-6gb       
          - c8-60gb-186  
          - p8-12gb      
          - c2-7.5gb-31  
          - p2-3gb       
          - c8-90gb-186  
          - p1-1.5gb     
          - c4-30gb-83   
          - c1-7.5gb-30  
          - c16-120gb-392
          - c4-15gb-83   
          - c2-15gb-31   
          - c16-60gb-392 
          - c16-90gb-392 
          - c8-30gb-186  
          - c4-45gb-83   
      default: p1-1.5gb
    headnode_flavor:
      type: string
      label: Instance flavor
      description: Type of flavor that defines virtual resources for headnode
      constraints:
        - allowed_values: 
          - p4-6gb       
          - c8-60gb-186  
          - p8-12gb      
          - c2-7.5gb-31  
          - p2-3gb       
          - c8-90gb-186  
          - p1-1.5gb     
          - c4-30gb-83   
          - c1-7.5gb-30  
          - c16-120gb-392
          - c4-15gb-83   
          - c2-15gb-31   
          - c16-60gb-392 
          - c16-90gb-392 
          - c8-30gb-186  
          - c4-45gb-83   
      default: p1-1.5gb
    keypair:
      type: string
      label: Keypair Name
      description: Name of preexisting keypair to use for ssh access to instances 
      
resources:
    
    headnode:
      type: headnode.yaml
      depends_on: compute_infrastructure
      properties:
        flavor: {get_param: headnode_flavor}
        image: {get_param: image}
        key_name: {get_param: keypair}
        internal_network: {get_param: internal_network}
        external_network: {get_param: external_network}
        sec_group: {get_param: security_group}
            
    compute_infrastructure:
      type: compute_node_cluster.yaml
      properties:
        internal_net: {get_param: internal_network} 
        flavor: { get_param: compute_flavor }
        image: { get_param: image }
        ssh_key: {get_param: keypair}
        cluster_size: {get_param: cluster_size}
        sec_group: {get_param: security_group}
        
outputs:
  access_ip:
    description: IP address to access head node and submit jobs
    value: {get_attr: [headnode, public_headnode_ip]}
