#####################################################################################################
# Script: cluster.yaml
# Author: Kyle Robertson
# Date: September 18, 2015
# Company: Worlcom Exchange Inc.
# Description: A HEAT template that deploys the networking resources for the autoscale_cluster_yaml
# stack
#####################################################################################################

heat_template_version: 2018-08-31
description: Homogenous compute cluster

parameters:
    # Networking parameters
    external_network_name:
      type: string
      label: External Network Name
      description: Name of the external network where floating IP's for environment exist
    internal_network_name:
      type: string
      label: Internal Network Name
      description: Name to give to the internal network created in this stack
      default: test-network
    internal_network_cidr:
      type: string
      label: Internal Network CIDR
      description: Subnet CIDR for the subnet within the internal network created in this stack
      default: 10.20.30.0/24
    security_group_name:
      type: string
      label: Instance Security Group Name
      description: Name of created security group that all instances are placed in
      default: default
    # Computing parameters
    max_cluster_size:
      type: number
      description: Minimum number of servers in the compute node cluster
      constraints:
        - range: {min: 2, max: 7}
      default: 7
    min_cluster_size:
      type: number
      description: Minimum number of servers in the compute node cluster
      constraints:
        - range: {min: 2, max: 7}
      default: 2
    image:
      type: string
      label: Image name or ID
      description: Bootable image used to boot all instances
      default: CentOS 7
    compute_flavor:
      type: string
      label: Instance flavor
      description: Type of flavor that defines virtual resources for compute nodes
      constraints:
        - allowed_values: 
          - c4-45gb-83
          - c2-15gb-31
          - c8-30gb-186
          - c4-30gb-83
          - c16-90gb-392
          - c2-7.5gb-31
          - c1-7.5gb-30
          - c8-90gb-186
          - c16-120gb-392
          - c8-60gb-186
          - c16-180gb-392
          - c4-15gb-83
          - c16-60gb-392
      default: c16-60gb-392
    headnode_flavor:
      type: string
      label: Instance flavor
      description: Type of flavor that defines virtual resources for headnode
      constraints:
        - allowed_values: 
          - c4-45gb-83
          - c2-15gb-31
          - c8-30gb-186
          - c4-30gb-83
          - c16-90gb-392
          - c2-7.5gb-31
          - c1-7.5gb-30
          - c8-90gb-186
          - c16-120gb-392
          - c8-60gb-186
          - c16-180gb-392
          - c4-15gb-83
          - c16-60gb-392
      default: c1-7.5gb-30
    keypair:
      type: string
      label: Keypair Name
      description: Name of preexisting keypair to use for ssh access to instances 
      
resources:
    cluster_networking:
      type: cluster_network.yaml
      properties:
        network_name: {get_param: internal_network_name}
        subnet_cidr: {get_param: internal_network_cidr}
        external_network: {get_param: external_network_name}
        # sec_group: {get_param: security_group}
        # key_name: {get_param: keypair}
            
    compute_infrastructure:
      type: compute_node_cluster.yaml
      depends_on:
        - cluster_networking
      properties:
        max_cluster_size: {get_param: max_cluster_size}
        min_cluster_size: {get_param: min_cluster_size}
        image: { get_param: image }
        flavor: { get_param: compute_flavor }
        internal_net: 
          get_attr:
            - cluster_networking
            - compute_net
        ssh_key: {get_param: keypair}
        sec_group:
          get_attr:
            - cluster_networking
            - cluster_sec_group

    headnode:
      type: headnode.yaml
      depends_on: 
        - cluster_networking
        - compute_infrastructure
      properties:
        flavor: {get_param: headnode_flavor}
        image: {get_param: image}
        key_name: {get_param: keypair}
        internal_network: 
          get_attr:
            - cluster_networking
            - compute_net
        external_network: {get_param: external_network_name}
        sec_group:
          get_attr:
            - cluster_networking
            - cluster_sec_group
        
outputs:
  access_ip:
    description: IP address to access head node and submit jobs
    value: {get_attr: [headnode, public_headnode_ip]}
  scale_up_url:
      value: {get_attr: [compute_infrastructure, scale_up_url]}
  scale_down_url:
      value: {get_attr: [compute_infrastructure, scale_down_url]}
  scale_up_signal_url:
      value: {get_attr: [compute_infrastructure, scale_up_signal_url]}
  scale_down_signal_url:
      value: {get_attr: [compute_infrastructure, scale_down_signal_url]}
  scale_up_info:
      value: {get_attr: [compute_infrastructure, scale_up_infolkjkk
  scale_down_info:
      value: {get_attr: [compute_infrastructure, scale_down_info]}
