#cloud-config

#####################################################################################################
# Script: compute_cloud-init.yaml
# Author: Kyle Robertson
# Date: September 18, 2015
# Company: Worlcom Exchange Inc.
# Description: A cloud init file for installing TORQUE and all its dependencies on compute nodes
#####################################################################################################

package-update: true
package-upgrade: true
packages:
  - python-pip
  - python3
  - python3-pip
final_message: "The system is finally up, after $UPTIME seconds"

