---
# This playbook contains common plays that will be run on all nodes.

- name: Update/upgrade existing packages
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    # upgrade: yes
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install packages
  become: yes
  become_method: sudo
  apt:
    name:
      - python-pip
      - python-dev
      - python3
      - python3-pip
      - python3-dev
      - libsuitesparse-dev
      - libfftw3-dev
      - libopenblas-dev
    state: latest
    force_apt_get: yes

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  become: yes
  become_method: sudo
  with_items: "{{ groups.all }}"

- name: Create /mnt/data directory
  become: yes
  become_method: sudo
  file: 
    path: /mnt/data
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes
