---
# This playbook contains common plays that will be run on all nodes.

- name: Change permissions on /data directory
  become: true
  become_method: sudo
  ansible.builtin.file: 
    path: /data
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: deploy dask scheduler service
  become: true
  become_method: sudo
  ansible.builin.template:
    src: dscheduler.service.j2
    dest: /usr/lib/systemd/system/dscheduler.service
