---
# This playbook contains common plays that will be run on all nodes.

- name: Change permissions on persistent volume mountpoint
  become: true
  become_method: sudo
  ansible.builtin.file: 
    path: "{{ persistent_volume_mountpoint }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes

- name: deploy dask scheduler service
  become: true
  become_method: sudo
  tags: ['dask']
  ansible.builtin.template:
    src: dask-scheduler.service.j2
    dest: /usr/lib/systemd/system/dask-scheduler.service

- name: start dask scheduler service
  become: true
  become_method: sudo
  tags: ['dask']
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: true
    name: dask-scheduler
