- name: Create /mnt/data directory
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /mnt/data
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: Ensure correct permissions on /tmp
  become: yes
  become_method: sudo
  # The normal settings for /tmp are 1777, which ls shows as drwxrwxrwt. That
  # is: wide open, except that only the owner of a file can remove it (that's
  # what this extra t bit means for a directory).
  ansible.builtin.file:
    path: /tmp
    state: directory
    mode: '1777'
