- name: Create Ceph config directory
  become: yes
  become_method: sudo
  tags: ["ceph"]
  ansible.builtin.file:
    path: "{{ ceph_config_directory }}"
    state: directory
    owner: root
    group: root
    recurse: yes

- name: Create Ceph share mountpoint at {{ ceph_share_mountpoint }}
  become: yes
  become_method: sudo
  tags: ["ceph"]
  ansible.builtin.file:
    path: "{{ ceph_share_mountpoint }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Create Ceph share key config file
  become: yes
  become_method: sudo
  tags: ["ceph"]
  ansible.builtin.template:
    src: ceph_fullkey_config.j2
    dest: "{{ ceph_config_directory }}/client.fullkey.{{ ceph_share_user }}"
    owner: root
    group: root

- name: Create Ceph share key file
  become: yes
  become_method: sudo
  tags: ["ceph"]
  ansible.builtin.template:
    src: ceph_keyonly_config.j2
    dest: "{{ ceph_config_directory }}/client.keyonly.{{ ceph_share_user }}"
    owner: root
    group: root

- name: Create Ceph config file
  become: yes
  become_method: sudo
  tags: ["ceph"]
  ansible.builtin.template:
    src: ceph.conf.j2
    dest: "{{ ceph_config_directory }}/ceph.conf"
    owner: root
    group: root

- name: Configure persistent Ceph mount
  become: yes
  become_method: sudo
  tags: ["ceph"]
  ansible.posix.mount:
    state: mounted
    fstype: ceph
    src: "{{ ceph_share_user }}@.{{ ceph_share_fs_name }}={{ ceph_share_subdirectory }}"
    path: "{{ ceph_share_mountpoint }}"
    opts: "secretfile={{ ceph_config_directory }}/client.keyonly.{{ ceph_share_user }}"

- name: Create per-user share directories
  become: yes
  become_method: sudo
  tags: ["ceph", "filesystem", "users"]
  ansible.builtin.file:
    path: "{{ ceph_share_mountpoint }}/{{ item['username'] }}"
    state: directory
    owner: "{{ item['username'] }}"
    group: "{{ item['username'] }}"
    recurse: yes
  loop: "{{ human_users }}"
