- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    # regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}.*{{ item }}$"
    # line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}"
    regexp: "{{ hostvars[item]['ansible_host'] }}.*{{ item }}$"
    line: "{{ hostvars[item]['ansible_host'] }} {{item}}"
    state: present
  become: yes
  become_method: sudo
  with_items: "{{ groups.all }}"
