---
# This playbook contains common plays that will be run on all nodes.

- name: Configure filesystem
  tags: ["disks"]
  import_tasks: configure_filesystem.yml

- name: Install packages
  tags: ["install_packages"]
  import_tasks: install_packages.yml

- name: Configure networking
  tags: ["networking"]
  import_tasks: configure_networking.yml

- name: Configure Ceph share
  tags: ["ceph"]
  import_tasks: configure_ceph_share.yml

- name: Configure Dask
  tags: ["dask"]
  import_tasks: configure_dask.yml


# - name: Upload dispy service file
#   tags: ['dispy']
#   become: yes
#   become_method: sudo
#   ansible.builtin.copy:
#     src: ../files/dispynode.service
#     dest: /etc/systemd/system/
#     owner: root
#     group: root

# - name: Upload template dispynode config file
#   tags: ['dispy']
#   become: yes
#   become_method: sudo
#   ansible.builtin.template:
#     src: dispynode.j2
#     dest: /etc/dispynode.conf
#     owner: root
#     group: root

# # Start the dispy systemd service on all nodes
# - name: Start dispy service
#   tags: ['dispy']
#   become: yes
#   become_method: sudo
#   ansible.builtin.systemd:
#     name: dispynode.service
#     daemon_reload: yes
#     state: restarted
#     enabled: no
