---
# This playbook deploys the whole application stack in this site.
- name: Deploy Dask cluster Heat stack
  hosts: localhost
  tasks: 
  - name: create stack
    openstack.cloud.stack:
      name: "def-jkrich-dask-cluster-stack"
      state: present
      template: "heat/cluster.yaml"
      environment:
      - heat/env.yaml

# We need to modify the MaxStartups and MaxSessions entries in the sshd_config
# file of the headnode before gathering facts and running the bulk of the
# playbook. This is because the ssh server randomly drops connections with a
# default rate of 30% after more then 10 unauthenticated connections have been
# made
- name: Modify sshd_config on headnode
  gather_facts: no
  hosts: login
  tasks:
    - name: Modify MaxStartups
      become: yes
      become_method: sudo
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^MaxStartups'
        line: 'MaxStartups 30:30:60'
        state: present

    - name: Modify MaxSessions
      become: yes
      become_method: sudo
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^MaxSessions'
        line: 'MaxSessions 30'
        state: present

    - name: Restart ssh server on headnode
      become: yes
      become_method: sudo
      service:
        name: ssh
        state: restarted

# Make nodes satisfy roles
- name: Apply Common Configuration To All Nodes
  hosts: all
  roles:
    - role: common
      tags: ['common']

- name: Setup Head Node
  hosts: login
  roles:
    - role: login
      tags: ['login']

- name: Deploy Optics Code
  hosts: all
  roles:
    - role: optics
      tags: ['optics']

