---
# All hosts in the inventory have access to these variables
ansible_ssh_user: ubuntu
ceph_config_directory: /etc/ceph
ceph_monitor_hosts: 
  - 10.30.201.3:6789
  - 10.30.202.3:6789
  - 10.30.203.3:6789
ceph_share_user: def-jkrich
ceph_share_fs_name: cephfs
ceph_share_subdirectory: /volumes/_nogroup/f5716c94-cf5a-4140-a7d1-01ed52448de3
ceph_share_mountpoint: /share
ceph_share_access_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61613034643064653366393866653630336631303839313661656237323233643861353365616439
          6236316634343764343965613462656432393830393066390a366661326137613066623032393035
          31386539653135343263626364643237373739346466356136353963616135643339343535623133
          3730636130376335660a376631363035366336356234643134343736353566316438306538643334
          63613563376234666136356531653530353830653963616339616262336432393336346538303633
          3738376239393761336535653435303534613461356263386334
persistent_volume_mountpoint: /scratch

apt_packages:
  # Sysadmin dependencies
  - zsh
  - htop
  - zip
  - tree
  - build-essential
  - unzip
  - vim
  - fio
  - jq
  # Ceph dependencies
  - ceph-common
  - ceph-fuse
  - python3-cephfs
  - libcephfs2
  - python3-ceph-argparse
  # S4 RCWA simulation dependencies
  - libsuitesparse-dev
  - libfftw3-dev
  - libopenblas-dev
  - libssl-dev
  - libffi-dev
  # Simudo dependencies
  - parallel
  - optipng
  - poppler-utils
  - meshio-tools
  - gmsh
  - libcephfs2
  - python3-cephfs
  - ceph-common
  - python3-ceph-argparse
  - ceph-fuse
  - cython3
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - python3-tk
  - python3-argh
  - python3-atomicwrites
  - python3-cached-property
  - python3-dolfin
  - python3-future
  - python3-h5py
  - python3-matplotlib
  - python3-meshio
  - python3-pandas
  - python3-petsc4py
  - python3-pint
  - python3-pprofile
  - python3-pytest
  - python3-scipy
  - python3-sortedcontainers
  - python3-sphinx
  - python3-sphinx-rtd-theme
  - python3-tabulate
  - python3-tqdm
  - python3-yaml
  - python3-yamlordereddictloader

global_pip_packages:
  - dask[complete]
  - suffix_trees 
  - mpl_render
  - generic_escape
  - simudo
  - dispy
  - psutil

dask_scheduler_port: 8786 
dask_dashboard_port: 8787
dask_log_file_path: /var/log/dask.log
dask_user: ubuntu

# Users to be created
human_users:
  - username: krobert
    full_name: Kyle Robertson
    groups: ["sudo", "dask_user"]
    append_groups: true
    authorized_ssh_keys:
      # Personal macbook key
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxJYFHBMrjA8R785ReUj3VcYIOpuUEUoUJaBi9gIcM5c4UFp3a3fS3pqVLF6u55kOx3JLGOiExZf86IhJKe7LN3vpsHVYDGmjErzEXrzxZGF+zbKgL57kwayYDDZc6A8m7XbrntmjVgrCBOHj4WE62LgiZHUHKOtS5YSmicd1XAuJ5uAj+46ceJw/J0fkAw+dACV0NAWJPlXZLxfmsUgn/LMSzQA1XiWVP46RMzyc8dvkRLzmcB2kSVUTa7ApAlDtLA0iqVtRnEkD0GRLWnWw1hUIMhIjGISXYryU2Dim1ZPMG4CVIbPGtHUTHNaeLE38EWdvJHPuygqpbNE0wpvZZ"
      # Westcloud public key
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCld26w9ZraowQrK8oSoogVEi5ekDHQ+h9UvWnxyl5YWHMAYmskkNn/5KUQZvb53e7kKIRmm8F+zeKDfoNlmZaNPbi7AswG4Vc3upl1O0xRVKHzOKfGlwcgcOOIoQ2Ma2cCurCL91xDssKb7Fizr88r3O/ElBO7OZI5gJQVu+3xxRpVEeDMRP5Xk2350di/nICDyMqTMdlxKotFwCAaZsFieRki75+KUkftzL3Oi3qceswtjVzJwehgBYsbo0B00pfYOtn83cU3pSzyDaqDExjJF4ti4fY+gUIHNWQlKApQ5+XIDJOOC3WZVuME0bOLnKc0dSWvRVOOZrCcRwQCMUrD" 
  - username: jkrich
    full_name: Jacob Krich
    groups: ["sudo", "dask_user"]
    append_groups: true
    authorized_ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCytOYn6zJyKMDYj5Sgi+gj+tMoiEMZ7auW2YjV7MTFrbcrdiigOaIkH30EEO636AxPn+BKTK+1NnLzqe+tjSt3O5jUPidAV2JezrIC9WmDoxeHyT5kjzJCHaQdWz9zZUASD5IpAP88Ini6TokWTXsB11Q7vVBbln6XjA3D+lMOmME0vDjke66dGsNbC+3AkSW0vKbHtvMKP7VodUBh2TWjTXbVKLO8Q8EzCsYqmWtcW1h3kSYGb05UIkLJ9USJCztT9t7lfdHvFWR//GrG6ZCqDrmrTRictP3J5o3nTRv6YmuOYHbmot1Ttt2kpuZONfZ12Bxw8pIjePDHa/O8QQrf jacob@Jacobs-iMac.local"
  - username: dxia
    full_name: Daisy
    groups: ["dask_user"]
    append_groups: true
